// //index.js
'use client'
import Head from "next/head";
import { useEffect, useState } from "react";
import Form from "../components/form";


// const Dashboard = () =>{
//   return (
//     <h2> dzialaj pls</h2>
//   )
// }

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description"
          content="Generated by create next app" />
        <meta name="viewport"
          content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            height: "100vh",
          }}>
          <Form />
        </div>
      </main>
    </>
  );
}